### PR TITLE
LPS-61955

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Michael,

Please create a MAVEN type ticket instead of an LPS and update your commit message accordingly.

Thanks.

**Comment by jonathanmccann** [comment]
Actually, seems like it is already reported under MAVEN-206. Please check to make sure and if so, just use that ticket.

**Comment by mbowerman** [comment]
The commit message has been updated.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Greg for further review: https://github.com/gamerson/liferay-maven-support/pull/21

**Pull request closed without merging**
